### ISSUE TITLE
Unconfigurable attribute for window.location

### ISSUE THREAD

**Issue by wuhengzhi** [MobileChromeApps/cordova-plugin-chrome-apps-bootstrap#5]
@agrieve Please look at https://codereview.chromium.org/1148803003, the attributes for window.location were made of Unforgeable, that is the attributes are unconfigurable.
In api/app/window.js,
```
  var hostDescriptor = {
    configurable: true,
    enumerable: true,
    get: function() {
      var parts = /^([^:]*):\/\/([^/]*)(\/[^#?]*)/.exec(this.href);
      return parts ? parts[2] : "";
    }
  };
```
```configurable: true``` should be removed or set to false.
This issue causes the CrossWalk black screen when use this plugin. Please look at https://crosswalk-project.org/jira/browse/XWALK-4554

**Comment by agrieve** [comment]
gopher: URLs are now live as of cca v0.7.3, which fixes this issue.

**Comment by scalasm** [comment]
Using 0.7.3 and still getting this issue :S

**Comment by agrieve** [comment]
Can you confirm what versions of plugins you have? should be:

    cordova-plugin-chrome-apps-runtime 2.0.0 "Chrome App Runtime"
    cordova-plugin-chrome-apps-bootstrap 3.0.1 "Chrome Apps Core"

(run `cca plugin ls`)

**Comment by scalasm** [comment]
mario@scalasm-nb:~/src/rd-tutorials/HelloAgain$ cca plugin ls
cca v0.7.3
cordova-plugin-background-app 2.0.2 "Background App"
cordova-plugin-blob-constructor-polyfill 1.0.2 "Blob constructor shim"
cordova-plugin-chrome-apps-bootstrap 3.0.1 "Chrome Apps Core"
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-i18n 2.0.1 "Chrome Apps I18n API"
cordova-plugin-chrome-apps-navigation 1.0.4 "Chrome Apps Navigation"
cordova-plugin-chrome-apps-runtime 2.0.0 "Chrome App Runtime"
cordova-plugin-chrome-apps-storage 1.0.4 "Chrome Apps Storage API"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-customevent-polyfill 1.0.5-dev "CustomEvent constuctor shim"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-xhr-blob-polyfill 1.0.3 "XHR Blob Response Type Polyfill"
org.chromium.cca-hooks 0.0.0 "undefined"

**Comment by agrieve** [comment]
Hmm, I don't see how this could be the same issue, as the code that replaces window.location has been deleted in these new plugins versions. Could you verify what the error in devtools is?

**Comment by scalasm** [comment]
I'm quite new to Cordova and Chome Apps so maybe I'm doing particularly stupid when following the guide. I updated to 0.7.4 and created an Hello World project from scratch and:

1) if I package & deploy the app by using "cca run android --device", the app runs ok on my device;
2) if I use the Chrome Dev Editor (for making use of the live deployment feature) I see the blank screen and on the logcat I'm always getting something like this:

D/SystemWebChromeClient(29861): : Line 0 : Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
I/chromium(29861): [INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
D/CordovaWebViewImpl(29861): onPageFinished(file:///data/data/org.chromium.appdevtool/files/apps/app1uun3rt/www/plugins/cordova-plugin-chrome-apps-bootstrap/chromeapp.html)
W/BindingManager(29861): Cannot call determinedVisibility() - never saw a connection for the pid: 29861
D/SystemWebChromeClient(29861): file:///data/data/org.chromium.appdevtool/files/apps/app1uun3rt/www/plugins/cordova-plugin-chrome-apps-bootstrap/api/app/window.js: Line 237 : Uncaught TypeError: Cannot redefine property: host
I/chromium(29861): [INFO:CONSOLE(237)] "Uncaught TypeError: Cannot redefine property: host", source: file:///data/data/org.chromium.appdevtool/files/apps/app1uun3rt/www/plugins/cordova-plugin-chrome-apps-bootstrap/api/app/window.js (237)

Any idea?

**Comment by scalasm** [comment]
For the chronicle:

mario@scalasm-nb:~/src/rd-tutorials/HelloChromeWorld$ cca plugin ls
cca v0.7.4
cordova-plugin-background-app 2.0.2 "Background App"
cordova-plugin-blob-constructor-polyfill 1.0.2 "Blob constructor shim"
cordova-plugin-chrome-apps-bootstrap 3.0.1 "Chrome Apps Core"
cordova-plugin-chrome-apps-common 1.0.7 "Chrome Apps Common Utils"
cordova-plugin-chrome-apps-i18n 2.0.1 "Chrome Apps I18n API"
cordova-plugin-chrome-apps-navigation 1.0.4 "Chrome Apps Navigation"
cordova-plugin-chrome-apps-runtime 2.0.0 "Chrome App Runtime"
cordova-plugin-chrome-apps-storage 1.0.4 "Chrome Apps Storage API"
cordova-plugin-crosswalk-webview 1.2.0 "Crosswalk WebView Engine"
cordova-plugin-customevent-polyfill 1.0.5-dev "CustomEvent constuctor shim"
cordova-plugin-file 2.1.0 "File"
cordova-plugin-inappbrowser 1.0.1 "InAppBrowser"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.0.0 "Whitelist"
cordova-plugin-xhr-blob-polyfill 1.0.3 "XHR Blob Response Type Polyfill"
org.chromium.cca-hooks 0.0.0 "undefined"

**Comment by agrieve** [comment]
Ahhh, problem is we haven't release a new Chrome App Developer Tool since the fix went in :(. I'll try to get to that soon.
